#
# Flight Deck entrypoint
#
# This is an Ansible playbook Flight Deck will run on container
# startup. Here, you can add whatever special steps you need to
# run when the container starts up. This is the best place for
# credentials as in k8s, these are mounted at runtime.
#
# Flight Deck will also look for a YAML "extra vars" file to
# pass to this playbook at: /config/web/flight-deck-web.yml
#
---
- hosts: flight-deck-web
  roles:
    # Sets up the container internally.
    - flight-deck-web-run
  tasks:
    # Grab key configurations from files.
    - name: Get the database name from file, if provided.
      set_fact:
        MYSQL_NAME: "{{ lookup('file', MYSQL_NAME_FILE, errors='strict') }}"
      when:
        - MYSQL_NAME_FILE is defined
    - name: Get the username from file, if provided.
      set_fact:
        MYSQL_USER: "{{ lookup('file', MYSQL_USER_FILE, errors='strict') }}"
      when:
        - MYSQL_USER_FILE is defined
    - name: Get the password from file, if provided.
      set_fact:
        MYSQL_PASS: "{{ lookup('file', MYSQL_PASS_FILE, errors='strict') }}"
      when:
        - MYSQL_PASS_FILE is defined
    - name: Get the hash salt from file, if provided.
      set_fact:
        HASH_SALT: "{{ lookup('file', MYSQL_PASS_FILE, errors='strict') }}"
      when:
        - HASH_SALT_FILE is defined

    # Configure Drupal.
    - name: Update $databases in settings.php
      lineinfile:
        dest: "/var/www/html/sites/default/settings.php"
        regexp: "^\\$databases = \\[\\];"
        line: |
          $databases['default']['default'] = [
            'database' => '{{ MYSQL_NAME }}',
            'username' => '{{ MYSQL_USER }}',
            'password' => '{{ MYSQL_PASS }}',
            'prefix' => '',
            'host' => '{{ MYSQL_HOST | default('mysql-0.mysql') }}',
            'port' => '{{ MYSQL_PORT | default('3306') }}',
            'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
            'driver' => 'mysql',
          ];
      when:
        - MYSQL_NAME is defined
        - MYSQL_USER is defined
        - MYSQL_PASS is defined
    - name: Update $config_directories in settings.php
      lineinfile:
        dest: "/var/www/html/sites/default/settings.php"
        regexp: "^\\$config_directories = \\[\\];"
        line: "$config_directories[CONFIG_SYNC_DIRECTORY] = '../config/sync';"
    - name: Update hash salt in settings.php
      lineinfile:
        dest: "/var/www/html/sites/default/settings.php"
        regexp: "^\\$settings = \\[\\'hash_salt\\'\\] = \\'\\';"
        line: "$settings['hash_salt'] = '{{ _hash_salt | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}';"
      vars:
        _hash_salt: "{{ HASH_SALT | default('averybadsalt') }}"
